# Get all 
http://localhost:3000/supplies



# Get ONE

http://localhost:3000/supplies/5bd761dcae323e45a93ccfe8


# POST: posted one dataset
http://localhost:3000/supplies/655c41911a713e512dc68967

# {
#        "saleDate": "2020-03-23T21:06:49.506Z",
#     "items": [{
#         "name": "lenovo laptop",
#         "tags": ["office", "equipment"],
#         "price": {
#             "$numberDecimal": "50.05"
#         },
#         "quantity": 2
#     }, {
#         "name": "notepad",
#         "tags": ["office", "writing", "school"],
#         "price": {
#             "$numberDecimal": "35.29"
#         },
#         "quantity": 700
#     }, {
#         "name": "marker",
#         "tags": ["writing", "office", "school", "stationary"],
#         "price": {
#             "$numberDecimal": "56.12"
#         },
#         "quantity": 5
#     }, {
#         "name": "crayons",
#         "tags": ["school", "travel", "kids"],
#         "price": {
#             "$numberDecimal": "77.71"
#         },
#         "quantity": 2
#     }, {
#         "name": "iphone chargers",
#         "tags": ["office", "writing", "school"],
#         "price": {
#             "$numberDecimal": "18.47"
#         },
#         "quantity": 12
#     }, {
#         "name": "chart paper",
#         "tags": ["stationary", "office", "general"],
#         "price": {
#             "$numberDecimal": "19.95"
#         },
#         "quantity": 8
#     }, {
#         "name": "glue sticks",
#         "tags": ["stationary", "office", "general"],
#         "price": {
#             "$numberDecimal": "8.08"
#         },
#         "quantity": 3
#     }, {
#         "name": "Stapler",
#         "tags": ["school", "general", "organization"],
#         "price": {
#             "$numberDecimal": "14.16"
#         },
#         "quantity": 3
#     }],
#     "storeLocation": "New York",
#     "customer": {
#         "gender": "F",
#         "age": 52,
#         "email": "koila@witwuta.sv",
#         "satisfaction": 4
#     },
#     "couponUsed": true,
#     "purchaseMethod": "Online"
# }